services:
  db:
    image: postgres:16-alpine
    container_name: next_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextapp
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/0-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nextapp"]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: next_web
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nextapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped
    tty: true

volumes:
  dbdata: